config/routes.rb
Rails.application.routes.draw do
  resources :shortened_urls
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :update, :destroy] do
    patch :rotate_api_key, on: :member
  end
  resources :shortened_urls, only: [:create, :destroy]
  get "/:short_url", to: "redirects#show", 
    constraints: { short_url: /[A-Za-z0-9]{9}/ }, 
    as: :redirect  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/shortened_url.rb
class ShortenedUrl < ApplicationRecord
  belongs_to :user
  validates :original_url, presence: true
  validates :short_url, presence: true, uniqueness: true, length: { is: 9 }, format: { with: /\A[a-zA-Z0-9]{9}\z/ }
  before_validation :ensure_short_url, on: :create

  private

  def ensure_short_url
     return if short_url.present?
    loop do
      candidate = SecureRandom.alphanumeric(9)
      unless self.class.exists?(short_url: candidate)
        self.short_url = candidate
        break
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :shortened_urls, dependent: :destroy

  validates :email, presence: true, uniqueness: true
  validates :api_key, presence: true, uniqueness: true

  before_validation :ensure_api_key, on: :create

  # generowanie losowego uuid i zapisywanie

  def rotate_api_key!
    update!(api_key: SecureRandom.uuid)
  end
  private

  # sprawdzanie czy jest klucz jest git

  def ensure_api_key
    self.api_key ||= SecureRandom.uuid
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  allow_browser versions: :modern

  protect_from_forgery with: :null_session

  include ActionController::HttpAuthentication::Token::ControllerMethods

  private

  def current_user
    @current_user
  end

  def authenticate
    authenticate_with_http_token do |token, _opts|
      @current_user = User.find_by(api_key: token)
    end
    render json: { error: "Nuh uh" }, status: :unauthorized unless @current_user
  end
end

app/controllers/redirects_controller.rb
class RedirectsController < ActionController::Base
  # tbh barely any idea tf i did here
  def show
    url = ShortenedUrl.find_by!(short_url: params[:short_url])
    redirect_to url.original_url, allow_other_host: true
  rescue ActiveRecord::RecordNotFound
    render plain: "Brak", status: :not_found
  end
end

app/controllers/shortened_urls_controller.rb
class ShortenedUrlsController < ApplicationController
  before_action :authenticate

  protect_from_forgery with: :null_session

  def index
    @shortened_urls = current_user.shortened_urls
  end

  def create
    url = current_user.shortened_urls.create!(original_url: params[:url])
    render json: { 
      short_code: url.short_url, 
      full: redirect_url(url.short_url) 
    }

  end

  def destroy
    url = current_user.shortened_urls.find(params[:id])
    url.destroy!
    head :no_content
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ActionController::HttpAuthentication::Token::ControllerMethods

  protect_from_forgery with: :null_session


  # sprawdzanie czy zalogowany z wyjatkiem tworzenia
  before_action :authenticate_with_api_key, except: :create
  skip_before_action :authenticate_with_api_key, only: :create

  # unprotected create
  def create
    user = User.create!(email: params[:email])
    render json: { id: user.id, email: user.email, api_key: user.api_key }
  end


  def update
    current_user.update!(email: params[:email])
    render json: { id: current_user.id, email: current_user.email }
  end

  # rotate api
  def rotate_api_key
    current_user.rotate_api_key!
    render json: { api_key: current_user.api_key }
  end

  # user delete
  def destroy
    current_user.destroy!
    head :no_content
  end

  private

  # Api auth
  def authenticate_with_api_key
    authenticate_or_request_with_http_token do |token, _options|
      @current_user = User.find_by(api_key: token)
    end
  end

  # current_user
  def current_user
    @current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shortened_urls_helper.rb
module ShortenedUrlsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Urlshortener" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shortened_urls/_form.html.erb
<%= form_with(model: shortened_url) do |form| %>
  <% if shortened_url.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(shortened_url.errors.count, "error") %> prohibited this shortened_url from being saved:</h2>

      <ul>
        <% shortened_url.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :original_url, style: "display: block" %>
    <%= form.text_field :original_url %>
  </div>

  <div>
    <%= form.label :short_url, style: "display: block" %>
    <%= form.text_field :short_url %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shortened_urls/_shortened_url.html.erb
<div id="<%= dom_id shortened_url %>">
  <p>
    <strong>Original url:</strong>
    <%= shortened_url.original_url %>
  </p>

  <p>
    <strong>Short url:</strong>
    <%= shortened_url.short_url %>
  </p>

  <p>
    <strong>User:</strong>
    <%= shortened_url.user_id %>
  </p>

</div>

app/views/shortened_urls/edit.html.erb
<% content_for :title, "Editing shortened url" %>

<h1>Editing shortened url</h1>

<%= render "form", shortened_url: @shortened_url %>

<br>

<div>
  <%= link_to "Show this shortened url", @shortened_url %> |
  <%= link_to "Back to shortened urls", shortened_urls_path %>
</div>

app/views/shortened_urls/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Shortened urls" %>

<h1>Shortened urls</h1>

<div id="shortened_urls">
  <% @shortened_urls.each do |shortened_url| %>
    <%= render shortened_url %>
    <p>
      <%= link_to "Show this shortened url", shortened_url %>
    </p>
  <% end %>
</div>

<%= link_to "New shortened url", new_shortened_url_path %>

app/views/shortened_urls/new.html.erb
<% content_for :title, "New shortened url" %>

<h1>New shortened url</h1>

<%= render "form", shortened_url: @shortened_url %>

<br>

<div>
  <%= link_to "Back to shortened urls", shortened_urls_path %>
</div>

app/views/shortened_urls/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @shortened_url %>

<div>
  <%= link_to "Edit this shortened url", edit_shortened_url_path(@shortened_url) %> |
  <%= link_to "Back to shortened urls", shortened_urls_path %>

  <%= button_to "Destroy this shortened url", @shortened_url, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :api_key, style: "display: block" %>
    <%= form.number_field :api_key %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Api key:</strong>
    <%= user.api_key %>
  </p>

</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Users" %>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<% content_for :title, "New user" %>

<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>